### ISSUE TITLE
Will the predicted_program participate in the calculation of the final score when submitting the prediction?

### ISSUE THREAD

**Issue by Kuroxiro** [psunlpgroup/MultiHiertt#3]
Will the predicted_program participate in the calculation of the final score when submitting the prediction?

**Comment by yilunzhao** [comment]
Hi @Kuroxiro, thanks for your interests in our work!

Yes, `"predicted_program"` will be used. you can check this [function](https://github.com/psunlpgroup/MultiHiertt/blob/a0f59261650f120d2c83b38d2b79cf8e352fea5b/evaluate.py#L70) to see how we process the predicted output and calculate the final score.
